### ISSUE TITLE
IE11 support broken

### ISSUE THREAD

**Issue by javier-godoy** [FlowingCode/RssItemsAddon#9]
When this addon is included in a Vaadin 14 project, compiled in production mode and browsed with IE11, the following error shows in the browser console:

```
ES5 bundle cannot be loaded:

SCRIPT5007: No se puede establecer la propiedad 'X2JS' de referencia nula o sin definir
vaadin-bundle.es5-726f6b861ab7362ac53f.cache.js (712,342762)
```

Removing RssItems from the project fixes the issue, which indicates there is some issue when RssItems is transpiled to ES5.

Indeed RssItems has a dependency with X2JS
https://github.com/FlowingCode/RssItemsAddon/blob/fd2c2a655d028f47953a459ff50234a62038150a/src/main/resources/META-INF/frontend/rss-items.js#L41
which makes this issue similar to x2js/x2js#61

Investigate isomorphic-xml2js as a possible workaround.

**Comment by javier-godoy** [comment]
Back to triage for reconsideration

**Comment by mlopezFC** [comment]
We will not support IE11. If someone needs it we can reopen this.
